POST http://localhost:8081/api/issue/my-card-id
Accept: application/json

###

POST http://localhost:8081/api/redeem/my-card-id
Content-Type: application/json

###

POST http://localhost:8081/api/redeem/my-card-id/insufficient
Content-Type: application/json

###

POST http://localhost:8081/api/redeem/my-card-id/negative
Content-Type: application/json

###

POST http://localhost:8081/api/issue/bulk
Content-Type: application/json

###